package com.api.entities;
// Generated 2015-11-11 0:53:01 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * NewsMsr generated by hbm2java
 */
@Entity
@Table(name = "news_msr", catalog = "cy_gold")
public class NewsMsr implements java.io.Serializable {

	private Integer newsId;
	private String newsName;
	private String status;
	private Integer startDate;
	private Integer startTime;
	private Integer endDate;
	private Integer endTime;
	private String newsText;
	private String hyperlink;
	private byte[] imageFile;
	private String imageExt;
	private String remark;
	private String autoSend;
	private String sendFreq;
	private Integer sendTime;
	private Integer sendDate;
	private Integer crtDate;
	private Integer crtTime;
	private Integer crtUser;
	private String crtUserName;
	private Integer updDate;
	private Integer updTime;

	public NewsMsr() {
	}

	public NewsMsr(String newsName, String status, Integer startDate, Integer startTime, Integer endDate,
			Integer endTime, String newsText, String hyperlink, byte[] imageFile, String imageExt, String remark,
			String autoSend, String sendFreq, Integer sendTime, Integer sendDate, Integer crtDate, Integer crtTime,
			Integer crtUser, String crtUserName, Integer updDate, Integer updTime) {
		this.newsName = newsName;
		this.status = status;
		this.startDate = startDate;
		this.startTime = startTime;
		this.endDate = endDate;
		this.endTime = endTime;
		this.newsText = newsText;
		this.hyperlink = hyperlink;
		this.imageFile = imageFile;
		this.imageExt = imageExt;
		this.remark = remark;
		this.autoSend = autoSend;
		this.sendFreq = sendFreq;
		this.sendTime = sendTime;
		this.sendDate = sendDate;
		this.crtDate = crtDate;
		this.crtTime = crtTime;
		this.crtUser = crtUser;
		this.crtUserName = crtUserName;
		this.updDate = updDate;
		this.updTime = updTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "NEWS_ID", unique = true, nullable = false)
	public Integer getNewsId() {
		return this.newsId;
	}

	public void setNewsId(Integer newsId) {
		this.newsId = newsId;
	}

	@Column(name = "NEWS_NAME", length = 50)
	public String getNewsName() {
		return this.newsName;
	}

	public void setNewsName(String newsName) {
		this.newsName = newsName;
	}

	@Column(name = "STATUS", length = 1)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Column(name = "START_DATE")
	public Integer getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Integer startDate) {
		this.startDate = startDate;
	}

	@Column(name = "START_TIME")
	public Integer getStartTime() {
		return this.startTime;
	}

	public void setStartTime(Integer startTime) {
		this.startTime = startTime;
	}

	@Column(name = "END_DATE")
	public Integer getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Integer endDate) {
		this.endDate = endDate;
	}

	@Column(name = "END_TIME")
	public Integer getEndTime() {
		return this.endTime;
	}

	public void setEndTime(Integer endTime) {
		this.endTime = endTime;
	}

	@Column(name = "NEWS_TEXT", length = 300)
	public String getNewsText() {
		return this.newsText;
	}

	public void setNewsText(String newsText) {
		this.newsText = newsText;
	}

	@Column(name = "HYPERLINK", length = 300)
	public String getHyperlink() {
		return this.hyperlink;
	}

	public void setHyperlink(String hyperlink) {
		this.hyperlink = hyperlink;
	}

	@Column(name = "IMAGE_FILE")
	public byte[] getImageFile() {
		return this.imageFile;
	}

	public void setImageFile(byte[] imageFile) {
		this.imageFile = imageFile;
	}

	@Column(name = "IMAGE_EXT", length = 10)
	public String getImageExt() {
		return this.imageExt;
	}

	public void setImageExt(String imageExt) {
		this.imageExt = imageExt;
	}

	@Column(name = "REMARK", length = 200)
	public String getRemark() {
		return this.remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	@Column(name = "AUTO_SEND", length = 1)
	public String getAutoSend() {
		return this.autoSend;
	}

	public void setAutoSend(String autoSend) {
		this.autoSend = autoSend;
	}

	@Column(name = "SEND_FREQ", length = 1)
	public String getSendFreq() {
		return this.sendFreq;
	}

	public void setSendFreq(String sendFreq) {
		this.sendFreq = sendFreq;
	}

	@Column(name = "SEND_TIME")
	public Integer getSendTime() {
		return this.sendTime;
	}

	public void setSendTime(Integer sendTime) {
		this.sendTime = sendTime;
	}

	@Column(name = "SEND_DATE")
	public Integer getSendDate() {
		return this.sendDate;
	}

	public void setSendDate(Integer sendDate) {
		this.sendDate = sendDate;
	}

	@Column(name = "CRT_DATE")
	public Integer getCrtDate() {
		return this.crtDate;
	}

	public void setCrtDate(Integer crtDate) {
		this.crtDate = crtDate;
	}

	@Column(name = "CRT_TIME")
	public Integer getCrtTime() {
		return this.crtTime;
	}

	public void setCrtTime(Integer crtTime) {
		this.crtTime = crtTime;
	}

	@Column(name = "CRT_USER")
	public Integer getCrtUser() {
		return this.crtUser;
	}

	public void setCrtUser(Integer crtUser) {
		this.crtUser = crtUser;
	}

	@Column(name = "CRT_USER_NAME", length = 50)
	public String getCrtUserName() {
		return this.crtUserName;
	}

	public void setCrtUserName(String crtUserName) {
		this.crtUserName = crtUserName;
	}

	@Column(name = "UPD_DATE")
	public Integer getUpdDate() {
		return this.updDate;
	}

	public void setUpdDate(Integer updDate) {
		this.updDate = updDate;
	}

	@Column(name = "UPD_TIME")
	public Integer getUpdTime() {
		return this.updTime;
	}

	public void setUpdTime(Integer updTime) {
		this.updTime = updTime;
	}

}
